### ISSUE TITLE
internal error: method type

### ISSUE THREAD

**Issue by livnev** [dapphub/dapptools#165] opened 2019-04-01 11:25 UTC
`hevm` throws this exception when running `dapp test -v` on commit `e6471d989221e55fbc88d45a421f75fe94de89c4` of [dss](https://github.com/makerdao/dss).

```
hevm: internal error: method type
CallStack (from HasCallStack):
  error, called at src/EVM/Solidity.hs:218:22 in hevm-0.28-CbAzYNsnEyLDxyLCdifpxA:EVM.Solidity
```

when using the latest `dapp`:

```
$ dapp --version
dapp 0.17.0
solc, the solidity compiler commandline interface
Version: 0.5.6+commit.b259423e.Linux.g++
```

**Comment by asymmetric** [comment] 2019-04-01 12:43
To repro: `dapp test -v -r test_drip_updates_rho`.

This happens on 0.16.0 too FWIW.

**Comment by desaperados** [comment] 2019-09-03 03:02
Can't reproduce on the latest release. Closing...

**Closed by desaperados** 2019-09-03 03:02 UTC
Labels: bug, hevm
