### ISSUE TITLE
Seth call fails to verify reverted calls

### ISSUE THREAD

**Issue by fabiohild** [dapphub/dapptools#536] opened 2020-11-05 23:21 UTC
When using seth call for a getter that reverts for some reason such as the one below, seth fails to recognize that the call reverted, and instead it returns the error bytes payload converted to the return variable type.

Example getter
```
    function getter() public view returns (uint) {
        if (msg.sender != 0x230E277B1A6B36d56Da0F143Fe73ABdA7a926dbb) revert("unauthorized");
        return 1;
    }
```
Non reverting calls succeed:
```
export ETH_FROM=0x230e277b1a6b36d56da0f143fe73abda7a926dbb
seth call 0xC70aE60A2DB6F56EfA5FcF6e1b63E9d39dB019C4 'getter()(uint256)'
1
```

Reverting calls erroneously return the uint representation of the returned revert reason:
```
export ETH_FROM=0x76E2cFc1F5Fa8F6a5b3fC4c8F4788F0116861F9B
seth call 0xC70aE60A2DB6F56EfA5FcF6e1b63E9d39dB019C4 'getter()(uint256)'
3963877391197344453575983046348115674221700746820753546331534351508065746944
```

The reverting call is returning the abi encoded (```Error(string)```) revert reason:
```0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000c756e617574686f72697a65640000000000000000000000000000000000000000```

Seth should check for the error signature (```0x08c379a```) and return the revert reason to the user.

**Comment by MrChico** [comment] 2020-11-06 14:58
Thanks for pointing this out!

**Comment by MrChico** [comment] 2020-11-06 16:25
actually a duplicate of #352

**Closed by MrChico** 2020-11-06 16:25 UTC
Labels: good first issue
