### ISSUE TITLE
Hash mismatch in fixed-output derivation

### ISSUE THREAD

**Issue by hujw77** [dapphub/dapptools#633] opened 2021-04-09 05:05 UTC
### Script
```shell
nix-env -f https://github.com/dapphub/dapptools/archive/master.tar.gz -iA solc-static-versions.solc_0_5_16
```

### Info 
```
replacing old 'solc-static-0.4.24'
installing 'solc-static-0.5.16'
these derivations will be built:
  /nix/store/wz49pby3vilj47c5zpl1khv3gqd39wh8-solc-macosx-amd64-v0.5.16+commit.9c3226ce.drv
  /nix/store/j0lpjwia94wrpb8qrrp3nqrj048bxh42-solc-static-0.5.16.drv
building '/nix/store/wz49pby3vilj47c5zpl1khv3gqd39wh8-solc-macosx-amd64-v0.5.16+commit.9c3226ce.drv'...

trying https://binaries.soliditylang.org/macosx-amd64/solc-macosx-amd64-v0.5.16+commit.9c3226ce
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28.9M  100 28.9M    0     0  5846k      0  0:00:05  0:00:05 --:--:-- 7269k
hash mismatch in fixed-output derivation '/nix/store/p89i75jpblwy53kfk3i7lw4hl5342sqk-solc-macosx-amd64-v0.5.16+commit.9c3226ce':
  wanted: sha256:13241n79dzzz5dfc3nqmji32622cw665240gppv6cn2qznw1rggp
  got:    sha256:0xdvlrw09hqb3i0bwcn9nyp4br15xr20gzlysaxl4wa913j28rlz
cannot build derivation '/nix/store/j0lpjwia94wrpb8qrrp3nqrj048bxh42-solc-static-0.5.16.drv': 1 dependencies couldn't be built
error: build of '/nix/store/j0lpjwia94wrpb8qrrp3nqrj048bxh42-solc-static-0.5.16.drv' failed
```

**Comment by MrChico** [comment] 2021-04-16 18:57
Thanks for reporting. This is quite odd and something I've also noticed. Do you have an idea of why this started to happen @xwvvvvwx ?

**Comment by xwvvvvwx** [comment] 2021-04-20 11:01
should be fixed by https://github.com/dapphub/dapptools/pull/635 once it lands.

**Comment by cameel** [comment] 2021-04-20 11:06
We had to rebuild older macOS binaries because they were not reporting the same version string as the original releases (and that's embedded in the bytecode so it would prevent successful verification). That PR has been sitting waiting for review for quite a file but it finally got merged last month and this is probably the cause here.

**Comment by xwvvvvwx** [comment] 2021-04-20 11:49
@cameel thanks for the clarification, much appreciated :pray: :sparkles:

**Closed** 2021-04-20 16:47 UTC
