### ISSUE TITLE
Support for signed negative numbers

### ISSUE THREAD

**Issue by eordano** [dapphub/dapptools#170] opened 2019-04-19 05:01 UTC
I'm trying to run:

```
seth --to-hex '-1'
```

Which clearly fails

```
seth---to-hex: error: bad number: `-1'
```

Because https://github.com/dapphub/dapptools/blob/master/src/seth/libexec/seth/seth---to-hex#L8 doesn't think the `-` is a valid part of a number.

My usecase is:
```
seth call 0xf87e31492faf9a91b02ee0deaad50d51d56d5d4d 'ownerOfLand(int256,int256)' 123 '-143'
```

Which should tell me who is the owner of the parcel 123,-143 in Decentraland... I know it's fairly uncommon to use signed integers in contracts, but I wonder if you would ever support something like this (my bash foo is not strong enough as to propose a PR)

Thanks for making this awesome tool!

**Comment by asymmetric** [comment] 2019-05-03 15:57
Closed by #172.

**Comment by rainbreak** [comment] 2019-05-03 17:46
Does #172 actually close this, or just partially address it?

**Comment by asymmetric** [comment] 2019-05-04 10:07
True:

```
❯ seth --to-hex (seth --to-int256 -9000)
seth---to-hex: error: missing `0x' prefix: `ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffdcd8'
```

**Comment by rainbreak** [comment] 2019-05-04 13:52
I think this is something that seth is inconsistent on. I think that all hex output should be given a `0x` prefix.

**Comment by asymmetric** [comment] 2019-05-04 19:38
The error message is actually incorrect. There's a [regexp](
https://github.com/dapphub/dapptools/tree/cb9cbcdcbe3d7449d122c4543013fa884517113a/src/seth/libexec/seth/seth---to-hex#L8-L9) to match against the hex digit character class, which [seems](https://www.regular-expressions.info/posixbrackets.html) to mean `[A-Fa-f0-9]`.

So a) the error message is wrong, and b) I'm not sure why -9000 (`ff...ff`) doesn't match the regexp.

**Comment by asymmetric** [comment] 2019-05-04 19:57
I had another look.

The usecase mentioned in the issue is satisfied by `seth---to-int256` - no need to pass it to `seth---to-hex`, as it's already in hex.

So I think the issue can actually be closed.

I can open another one to deal with the `0x` prefix.

**Comment by eordano** [comment] 2019-05-05 00:41
Thank you!

**Closed** 2019-05-05 00:42 UTC
Labels: enhancement
